source "https://rubygems.org"

ruby "3.4.9"

# Core
gem "rails", "~> 8.1.3"
gem "pg", "~> 1.1"
gem "csv"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
# Auth
gem "jwt"
gem "bcrypt", "~> 3.1.7"

# Environment variables
gem "dotenv-rails"

# CORS (allow React frontend)
gem "rack-cors"

# Serializer
gem "active_model_serializers"

# Windows timezone data
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows x64_mingw ]
end

group :development do
  gem "rubocop-rails-omakase", require: false
end